{% set name = "bloptools" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bloptools-{{ version }}.tar.gz
  sha256: eaee59c7d52a7fb3207f04e49bad5837fe4c685390145d4e6be68a4bfcffcb85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatch-vcs
    - hatchling
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - bluesky
    - botorch
    - databroker
    - gpytorch
    - h5py
    - matplotlib-base
    - numpy
    - ophyd
    - ortools-python
    - pytables
    - pytorch
    - scipy

test:
  imports:
    # The list of imports is generated via the following command:
    #   $ cd <blop-repo>
    #   $ find src/blop -name "*.py" | grep -v tests | sed 's/.__init__.py//g' | sed 's/._version//g' | sed 's;/;.;g' | sed 's/\.py//g'| sort -u
    - src.blop
    - src.blop.agent
    - src.blop.bayesian
    - src.blop.bayesian.acquisition
    - src.blop.bayesian.acquisition.analytic
    - src.blop.bayesian.acquisition.monte_carlo
    - src.blop.bayesian.kernels
    - src.blop.bayesian.models
    - src.blop.de
    - src.blop.de.de_opt_utils
    - src.blop.de.de_optimization
    - src.blop.de.hardware_flyer
    - src.blop.digestion
    - src.blop.dofs
    - src.blop.objectives
    - src.blop.plans
    - src.blop.plotting
    - src.blop.utils
    - src.blop.utils.functions
    - src.blop.utils.misc
    - src.blop.utils.prepare_re_env
  commands:
    # - pip check || echo "No problem"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/blop
  summary: Beamline optimization with machine learning
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://nsls-ii.github.io/blop

extra:
  recipe-maintainers:
    - mrakitin
    - AbbyGi
    - thomaswmorris
    - conda-forge/event-model
