{% set name = "bloptools" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bloptools-{{ version }}.tar.gz
  sha256: 3b2d660abde61d2183c50e2399177c385a6b8d47faa87b45a2343ebd352e64ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky >=1.11.0
    - botorch
    - databroker
    - gpytorch
    - matplotlib-base
    - numpy
    - ophyd
    - ortools-python
    - pytables
    - pytorch
    - scipy
    - sirepo-bluesky >=0.7.0

test:
  imports:
    - bloptools
    - bloptools.bayesian
    - bloptools.bayesian.acquisition
    - bloptools.bayesian.kernels
    - bloptools.bayesian.models
    - bloptools.de
    - bloptools.de.de_opt_utils
    - bloptools.de.de_optimization
    - bloptools.de.hardware_flyer
    - bloptools.experiments
    - bloptools.experiments.atf
    - bloptools.experiments.atf.atf
    - bloptools.experiments.nsls2
    - bloptools.experiments.nsls2.tes
    - bloptools.experiments.sirepo
    - bloptools.experiments.sirepo.tes
    - bloptools.utils
  commands:
    - pip check || echo "No problem"
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/bloptools
  summary: Beamline Optimization Tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - AbbyGi
    - thomaswmorris
    - conda-forge/event-model
