{% set name = "bloptools" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bloptools-{{ version }}.tar.gz
  sha256: eaee59c7d52a7fb3207f04e49bad5837fe4c685390145d4e6be68a4bfcffcb85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatch-vcs
    - hatchling
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - bluesky
    - botorch
    - databroker
    - gpytorch
    - h5py
    - matplotlib-base
    - numpy
    - ophyd
    - ortools-python
    - pytables
    - pytorch
    - scipy
    - zict <3.0.0

test:
  imports:
    - blop
    - blop.agent
    - blop.bayesian
    - blop.bayesian.acquisition
    - blop.bayesian.acquisition.analytic
    - blop.bayesian.acquisition.monte_carlo
    - blop.bayesian.kernels
    - blop.bayesian.models
    - blop.bayesian.plotting
    - blop.bayesian.transforms
    - blop.de
    - blop.de.de_opt_utils
    - blop.de.de_optimization
    - blop.de.hardware_flyer
    - blop.digestion
    - blop.dofs
    - blop.experiments
    - blop.experiments.atf
    - blop.experiments.atf.atf
    - blop.experiments.nsls2
    # - blop.experiments.nsls2.iss
    - blop.experiments.nsls2.tes
    - blop.experiments.sirepo
    - blop.experiments.sirepo.tes
    - blop.objectives
    - blop.plans
    - blop.utils
    - blop.utils.functions
    - blop.utils.misc
    - blop.utils.prepare_re_env
  commands:
    - pip check || echo "No problem"
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/blop
  summary: Beamline optimization with machine learning
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://nsls-ii.github.io/blop

extra:
  recipe-maintainers:
    - mrakitin
    - AbbyGi
    - thomaswmorris
    - conda-forge/event-model
